### PR TITLE
Save stripe_charge_id in Postcards & detect failed payment

### LINKED ISSUE #9: Set stripe_charge_id in Postcard model
* Create new column
* Associate after charge request in payments_controller

### PR DESCRIPTION
**Pull request by TimKJones**
fixes #9 

* Updates `postcard.stripe_charge_id` after a payment is created.
* Updates `flash` message after an unsuccessful payment.

### CODE REVIEW

File: app/controllers/builder_controller.rb [hunk 1]
```diff
@@ -71,19 +72,32 @@ def caption_params
   end
 
   def create_charge
+    charge = process_stripe_charge
+    postcard.update_attribute(:stripe_charge_id, charge[:id])
+    flash[:notice] = 'Your photo has been sent!'
+  rescue StandardError
```
Comment (TimKJones) [inline app/controllers/builder_controller.rb]: Stripe provides a few different error classes to help us give more informed error messages, but I didn't want to invest in that yet.

**Comment by TimKJones** [comment]
@edance this might also resolve #28 depending on how the flash message is displayed

**Comment by TimKJones** [comment]
Ugh, I rushed at the end before calling it a night and pushed up the last commit on this branch rather than making a new PR (the one that resolves #27 ). I haven't fully tested the `after_commit` triggering yet in the last commit.

Wanted to at least push this up in case it blocks you over the weekend when I'm unavailable. If not you can just leave this open and I'll get to it next week.
